# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: drupal
  drupal:
    image: drupal:9.5.3
    ports:
      - 8080:80
    volumes:
      - ./modules:/var/www/html/modules
      - ./themes:/var/www/html/themes
    restart: always