# Schema for the configuration files of the exlink module.

perimeter.settings:
  type: config_object
  label: 'Perimeter Settings'
  mapping:
    not_found_exception_patterns:
      type: sequence
      label: 'A list of regex patterns'
      sequence:
        - type: string
        - label: 'A regex pattern'
