socialblock.settings:
  type: config_object
  label: 'IBM Social Block settings'
  mapping:
    socialblock:
      type: mapping
      mapping:
        credentials:
          type: text
          label: 'Encrypted Twitter credentials'
block.settings.socialblock_block:
  type: block_settings
  label: 'IBM Social Block block'
  mapping:
    socialblock_block_settings:
